<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/PerformanceAgent.BenchmarkDotNet/PerformanceAgent.BenchmarkDotNet.csproj" />
    <ProjectReference Include="../../../src/PerformanceAgent.Core/PerformanceAgent.Core.csproj" />
  </ItemGroup>
</Project>
