using System.Globalization;
using PerformanceAgent.Core.Analysis;
using PerformanceAgent.Core.Budgets;

namespace PerformanceAgent.Cli;

/// <summary>
/// Presents <c>perfagent analyze</c> output. Measured facts and the authoritative verdict come first and are
/// labelled as such; model-generated text follows in a separate, explicitly advisory section.
/// </summary>
internal static class AnalysisConsoleWriter
{
    public static void Write(TextWriter output, AnalyzeResult result)
    {
        var deterministic = result.Deterministic;
        var verdict = Verdict(deterministic);
        var budget = deterministic.Budget;

        output.WriteLine("Performance analysis");
        output.WriteLine();
        output.WriteLine($"Candidate: {deterministic.CandidateRunId}");
        output.WriteLine($"Baseline:  {deterministic.BaselineRunId} (Current)");
        output.WriteLine($"Budget:    mean {Threshold(budget.MaxMeanRegressionPercent)}, allocation {Threshold(budget.MaxAllocationRegressionPercent)} ({deterministic.BudgetSource})");
        output.WriteLine();
        output.WriteLine($"Deterministic result: {verdict}");
        output.WriteLine();

        var regressions = deterministic.Check.Benchmarks.Where(x => !x.Result.Passed).ToArray();
        output.WriteLine("Measured regressions:");
        if (regressions.Length == 0)
            output.WriteLine("  (none)");
        foreach (var item in regressions)
            WriteMeasured(output, item, budget);

        var passed = deterministic.Check.Benchmarks.Where(x => x.Result.Passed).ToArray();
        if (passed.Length > 0)
        {
            output.WriteLine();
            output.WriteLine("Measured within budget:");
            foreach (var item in passed)
                WriteMeasured(output, item, budget);
        }

        output.WriteLine();
        if (result.Analysis is null)
        {
            output.WriteLine("AI analysis: unavailable (see error). The deterministic result above is unaffected.");
            return;
        }

        var analysis = result.Analysis;
        output.WriteLine("AI analysis (advisory; generated by a model, not measured):");
        WriteSection(output, "Summary:", [analysis.Summary]);
        var measured = deterministic.Check.Benchmarks.ToDictionary(x => x.Name, StringComparer.Ordinal);
        WriteSection(output, "Measured evidence cited by the model (values from Performance Agent's measurements, not the model):",
            analysis.EvidenceReferences.Select(x => CitedEvidence(x, measured, budget)));
        WriteSection(output, "Hypotheses (unverified; not measured facts):",
            analysis.Hypotheses.Select(x => x.Rationale is null ? $"- {x.Statement}" : $"- {x.Statement}\n  Rationale: {x.Rationale}"));
        WriteSection(output, "Suggested experiments (verify by benchmarking):",
            analysis.SuggestedExperiments.Select(x => x.ExpectedSignal is null ? $"- {x.Description}" : $"- {x.Description}\n  Expected signal: {x.ExpectedSignal}"));
        WriteSection(output, "Uncertainty:", analysis.Uncertainty is { } uncertainty && !string.IsNullOrWhiteSpace(uncertainty) ? [uncertainty] : []);
        output.WriteLine();
        output.WriteLine($"Deterministic result (authoritative): {verdict}");
    }

    public static string Verdict(DeterministicAnalysisResult deterministic) =>
        deterministic.Check.Passed ? "PASS" : "REGRESSION";

    private static void WriteMeasured(TextWriter output, BenchmarkCheckResult item, PerformanceBudget budget)
    {
        var (mean, allocation) = CheckFormatting.FormatMeasured(item.Result, budget);
        // Benchmark names come from evidence files and may contain control characters; keep them on one line.
        output.WriteLine($"  {SingleLine(item.Name)}: {(item.Result.Passed ? "PASS" : "FAIL")}");
        output.WriteLine($"    Mean: {mean}");
        output.WriteLine($"    Allocation: {allocation}");
    }

    // A citation shows measured values computed from evidence; the model's text is only a single-line, labelled note,
    // so it cannot pose as (or add lines that look like) a measured value.
    private static string CitedEvidence(AnalysisEvidenceReference reference, IReadOnlyDictionary<string, BenchmarkCheckResult> measured, PerformanceBudget budget)
    {
        var values = measured.TryGetValue(reference.BenchmarkName, out var item) && CheckFormatting.FormatMeasured(item.Result, budget) is var (mean, allocation)
            ? $"\n  Mean: {mean}\n  Allocation: {allocation}"
            : "\n  No measured comparison available.";
        return $"- {SingleLine(reference.BenchmarkName)}{values}\n  AI note: {SingleLine(reference.Observation)}";
    }

    private static void WriteSection(TextWriter output, string heading, IEnumerable<string> entries)
    {
        output.WriteLine();
        output.WriteLine($"  {heading}");
        var any = false;
        foreach (var entry in entries)
        {
            any = true;
            foreach (var line in Sanitize(entry).Split('\n'))
                output.WriteLine($"    {line}");
        }

        if (!any)
            output.WriteLine("    (none)");
    }

    // Model output is untrusted text: keep line breaks for layout, drop other control characters
    // (including ANSI escape sequences' ESC) so it cannot rewrite or spoof earlier terminal output.
    internal static string Sanitize(string text) =>
        new(text.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Where(c => c == '\n' || !char.IsControl(c))
            .ToArray());

    /// <summary><see cref="Sanitize"/> plus line breaks collapsed to spaces.</summary>
    internal static string SingleLine(string text) =>
        string.Join(' ', Sanitize(text).Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries));

    private static string Threshold(double? percent) =>
        percent is null ? "not configured" : $"+{percent.Value.ToString("0.##", CultureInfo.InvariantCulture)}%";
}
