using System.Globalization;
using PerformanceAgent.Core.Analysis;
using PerformanceAgent.Core.Budgets;

namespace PerformanceAgent.Cli;

/// <summary>
/// Presents <c>perfagent analyze</c> output. Measured facts and the authoritative verdict come first and are
/// labelled as such; model-generated text follows in a separate, explicitly advisory section.
/// </summary>
internal static class AnalysisConsoleWriter
{
    public static void Write(TextWriter output, AnalyzeResult result)
    {
        var deterministic = result.Deterministic;
        var verdict = Verdict(deterministic);
        var budget = deterministic.Budget;

        output.WriteLine("Performance analysis");
        output.WriteLine();
        output.WriteLine($"Candidate: {deterministic.CandidateRunId}");
        output.WriteLine($"Baseline:  {deterministic.BaselineRunId} (Current)");
        output.WriteLine($"Budget:    mean {Threshold(budget.MaxMeanRegressionPercent)}, allocation {Threshold(budget.MaxAllocationRegressionPercent)} ({deterministic.BudgetSource})");
        output.WriteLine();
        output.WriteLine($"Deterministic result: {verdict}");
        output.WriteLine();

        var regressions = deterministic.Check.Benchmarks.Where(x => !x.Result.Passed).ToArray();
        output.WriteLine("Measured regressions:");
        if (regressions.Length == 0)
            output.WriteLine("  (none)");
        foreach (var item in regressions)
            WriteMeasured(output, item, budget);

        var passed = deterministic.Check.Benchmarks.Where(x => x.Result.Passed).ToArray();
        if (passed.Length > 0)
        {
            output.WriteLine();
            output.WriteLine("Measured within budget:");
            foreach (var item in passed)
                WriteMeasured(output, item, budget);
        }

        output.WriteLine();
        if (result.Analysis is null)
        {
            output.WriteLine("AI analysis: unavailable (see error). The deterministic result above is unaffected.");
            return;
        }

        var analysis = result.Analysis;
        output.WriteLine("AI analysis (advisory; generated by a model, not measured):");
        WriteSection(output, "Summary:", [analysis.Summary]);
        WriteSection(output, "Evidence (as cited by the model; measured values are listed above):",
            analysis.EvidenceReferences.Select(x => $"- {x.BenchmarkName}: {x.Observation}"));
        WriteSection(output, "Hypotheses (unverified; not measured facts):",
            analysis.Hypotheses.Select(x => x.Rationale is null ? $"- {x.Statement}" : $"- {x.Statement}\n  Rationale: {x.Rationale}"));
        WriteSection(output, "Suggested experiments (verify by benchmarking):",
            analysis.SuggestedExperiments.Select(x => x.ExpectedSignal is null ? $"- {x.Description}" : $"- {x.Description}\n  Expected signal: {x.ExpectedSignal}"));
        WriteSection(output, "Uncertainty:", analysis.Uncertainty is { } uncertainty && !string.IsNullOrWhiteSpace(uncertainty) ? [uncertainty] : []);
        output.WriteLine();
        output.WriteLine($"Deterministic result (authoritative): {verdict}");
    }

    public static string Verdict(DeterministicAnalysisResult deterministic) =>
        deterministic.Check.Passed ? "PASS" : "REGRESSION";

    private static void WriteMeasured(TextWriter output, BenchmarkCheckResult item, PerformanceBudget budget)
    {
        var result = item.Result;
        output.WriteLine($"  {item.Name}: {(result.Passed ? "PASS" : "FAIL")}");
        output.WriteLine($"    Mean: {CheckFormatting.FormatChange(result.Comparison.Mean)}{CheckFormatting.FormatBudget(budget.MaxMeanRegressionPercent, result.MeanExceeded)}");
        output.WriteLine($"    Allocation: {CheckFormatting.FormatChange(result.Comparison.AllocatedBytes)}{CheckFormatting.FormatBudget(budget.MaxAllocationRegressionPercent, result.AllocationExceeded)}");
    }

    private static void WriteSection(TextWriter output, string heading, IEnumerable<string> entries)
    {
        output.WriteLine();
        output.WriteLine($"  {heading}");
        var any = false;
        foreach (var entry in entries)
        {
            any = true;
            foreach (var line in Sanitize(entry).Split('\n'))
                output.WriteLine($"    {line}");
        }

        if (!any)
            output.WriteLine("    (none)");
    }

    // Model output is untrusted text: keep line breaks for layout, drop other control characters
    // (including ANSI escape sequences' ESC) so it cannot rewrite or spoof earlier terminal output.
    private static string Sanitize(string text) =>
        new(text.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Where(c => c == '\n' || !char.IsControl(c))
            .ToArray());

    private static string Threshold(double? percent) =>
        percent is null ? "not configured" : $"+{percent.Value.ToString("0.##", CultureInfo.InvariantCulture)}%";
}
