<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.10.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PerformanceAgent.Core/PerformanceAgent.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PerformanceAgent.AI.Tests" />
  </ItemGroup>
</Project>
